
export const TEXT = {
  COMMON: {
    APP_NAME: "Hypo",
    CURRENCY_KRW: "원",
    CURRENCY_USD: "$",
    PERCENT: "%",
    BTN_NEXT: "다음",
    BTN_CONFIRM: "확인",
    BTN_CANCEL: "취소",
    BTN_CLOSE: "닫기",
    LOADING: "로딩 중...",
  },
  ACTIONS: {
    BUY: "더 담기 (구매)",
    SELL: "덜어내기 (판매)",
    HOLD: "그대로 두기 (보유)",
    WATCH: "지켜보기",
    REVISE: "생각 고쳐먹기 (전략 수정)",
    EXECUTE: "계획대로 실행",
  },
  TAB: {
    INSIGHT: "투데이",
    MY_THESIS: "아이디어",
    DISCOVERY: "발견",
  },
  INSIGHT: {
    HEADER_TODAY: "투데이",
    HEADER_MY_ASSET: "내 자산 현황",
    SUBHEADER_TODAY: "오늘의 시장 날씨",
    SUBHEADER_MY_ASSET: "나의 투자 성과 요약",
    TOTAL_ASSET: "내 투자 현황",
    BTN_VIEW_MY_STOCKS: "내 종목 보기",
    SECTION_DOMESTIC: "국내주식",
    SECTION_OVERSEAS: "해외주식",
  },
  MY_THESIS: {
    HEADER_TITLE: "아이디어",
    HEADER_DESC: (name: string) => `${name}님의 투자 가설들입니다.`,
    BTN_ADD_NEW: "+ 새 아이디어 추가",
    BADGE_URGENT: "대응 필요",
    BADGE_WATCHING: "WATCHING",
    STATUS_NO_EVENTS: "특이사항 없음",
    LABEL_D_DAY: (day: string) => day === 'D-1' ? '내일' : day,
  },
  STOCK_DETAIL: {
    CHART_TITLE: "주가 흐름",
    CHART_LOADING: "차트 데이터 로딩 중",
    LOGIC_TITLE: "내 가설 관리",
    BTN_ADD_LOGIC: "+ 새로운 가설 추가하기",
    NEWS_TITLE: "관련 뉴스",
    NEWS_EMPTY: "현재 분석된 주요 뉴스가 없습니다.",
    COMPANY_INFO_TITLE: "무엇을 하는 회사인가요?",
    BTN_EXPAND: "더 자세히 보기",
    BTN_COLLAPSE: "접기",
    BTN_LEARNING_RETURN: "분석 완료 (질문으로 돌아가기)",
    CTA_BUILD_THESIS: "이 종목으로 투자 가설 세우기",
    ACTION_LOG_TITLE: "지난 대응 내역 (Action Log)",
    EVENT_STEP_1: "Step 1. 정보",
    EVENT_STEP_2: "Step 2. 시장 반응",
    EVENT_STEP_3: "Step 3. Hypo의 분석",
    EVENT_STEP_4: "Step 4. 맥락 (Context)",
    EVENT_STEP_5: "Step 5. 대응 제안",
    BTN_SAVE_STRATEGY: "전략 저장 및 완료",
    BTN_RESELECT: "다시 선택하기",
  },
  DISCOVERY: {
    HEADER_TITLE: "발견",
    HEADER_DESC: "새로운 투자 기회와 시나리오",
    SEARCH_PLACEHOLDER: "기업, 키워드 검색 (예: 000660)",
    SECTION_RECENT: "최근 검색",
    SECTION_TRENDING: "주목할 시나리오",
    BTN_DETAIL: "상세 분석",
    EMPTY_SEARCH: "검색 결과가 없습니다.",
  },
  ONBOARDING: {
    SPLASH_TAGLINE: "감이 아닌, 논리로.",
    PERMISSION_TITLE: "단순한 시세 변동이 아니라\n내 가설에 대한 시사점을 알려드릴게요.",
    PERMISSION_DESC: (name: string) => `"${name}님의 판단을 기다립니다."`,
  },
};
